services:
  bd-server:
    image: mysql:8.0.39-debian
    environment:
      - MYSQL_ROOT_PASSWORD=clave123
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
  db-postgres:
    image: postgres:16.4-alpine3.20
    environment:
      - POSTGRES_PASSWORD=clave111
    ports:
      - "3307:5432"